name: Acquire activation file
on:
  workflow_dispatch: {}

jobs:
  request_file:
    name: Request manual activation file (.alf) 
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout repository kamu
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Meminta file .alf menggunakan versi terbaru (v4)
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v4

      # Langkah 3: Mengunggah file .alf menggunakan versi terbaru (v4)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}